import Head from 'next/head'
import React from 'react'
import { RiShoppingCartLine } from 'react-icons/ri'
import Footer from './Footer'
import Header from './Header'
import Link from 'next/link'
import { CategoryProps } from '../services/api/requests'

interface LayoutProps {
    children: React.ReactNode
    title: string
    wrapperClassName?: string
    ignoreFooterMarginTop?: boolean
    categories: CategoryProps[]
}

const Layout: React.FC<LayoutProps> = ({
    children,
    title,
    ignoreFooterMarginTop,
    wrapperClassName = '',
    categories = [],
}) => {
    return (
        <div
            className={'bg-gray-50 flex flex-col'}
            style={{ minHeight: '100vh' }}
        >
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header categories={categories} />
            <div className={`${wrapperClassName} relative`}>
                {children}
                <Link href={'/cart'} passHref>
                    <div
                        className={
                            ' bg-red-500 cursor-pointer flex sm:hidden hover:bg-red-600 active:bg-red-700 text-white items-center justify-center fixed left-8 bottom-8 z-50 w-14 h-14 rounded-xl shadow-xl'
                        }
                    >
                        <RiShoppingCartLine size={25} color={'#fff'} />
                    </div>
                </Link>
            </div>
            <Footer ignoreMarginTop={ignoreFooterMarginTop} />
        </div>
    )
}

export default Layout
